name: Add GitLocalize as co-author and auto merge

on:
  pull_request:
    types:
      - opened

jobs:
  add-gitlocalize-as-co-author-and-auto-merge:
    if: startsWith(github.head_ref, 'gitlocalize-')
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      pull-requests: write
      contents: write

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      COMMIT_MESSAGE: commit-message.txt

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Checkout to PR ref branch and amend commit message
        run: |
          git pull origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git log ${{ github.event.pull_request.head.sha }} -n 1 --pretty="%s" > $COMMIT_MESSAGE
          echo "" >> $COMMIT_MESSAGE
          echo "" >> $COMMIT_MESSAGE
          echo "Co-authored-by: gitlocalize-app[bot] <55277160+gitlocalize-app[bot]@users.noreply.github.com>" >> $COMMIT_MESSAGE
          echo "Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" >> $COMMIT_MESSAGE
          cat $COMMIT_MESSAGE
          git config user.name $(git log ${{ github.event.pull_request.head.sha }} -n 1 --pretty="%an")
          git config user.email $(git log ${{ github.event.pull_request.head.sha }} -n 1 --pretty="%ae")
          git commit --amend -F $COMMIT_MESSAGE
          git push -f origin ${{ github.head_ref }}
          rm $COMMIT_MESSAGE

      - name: Rebase and merge
        run: |
          gh pr review $PR_NUMBER --approve
          gh pr merge $PR_NUMBER --rebase
