name: Generate mo files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "bot_cps/locale/**.po"

jobs:
  generate_mo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run generating .mo scripts
        run: |
          ls -d bot_cps/locale/*/LC_MESSAGES/*.po | grep -v "en-GB" | xargs python i18n/msgfmt.py

      - name: Stage and count changes
        id: staging
        run: |
          ls -d bot_cps/locale/*/LC_MESSAGES/*.mo | grep -v "en-GB" | xargs git add
          echo "NUM_OF_STAGED=$(git diff --staged --name-only | wc -l)" >> $GITHUB_OUTPUT

      - name: Push to master
        if: steps.staging.outputs.NUM_OF_STAGED > 0
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          ls -d bot_cps/locale/*/LC_MESSAGES/*.mo | grep -v "en-GB" | xargs git add
          git commit -m "[actions] Update mo files"
          git push
